"""
ui/report_texts.py
==================
Bilingual (English / Portuguese) text content for the Comparative Analysis
PDF report. The language used when generating the report is whichever one
is active in the app at export time (see i18n.get_language(), consulted by
ui/report_exporter.py).
"""

# ── Placeholder content ──────────────────────────────────────────────────────
# Intentionally NOT translated — same treatment as the author/repository
# placeholders elsewhere in the project. These are filled in by the user
# regardless of the active UI language.

MEMBERS     = [
    "Guilherme Carvalho Alvarenga",
    "Lara Hydalgo Ferreira"
]
INSTITUTION = " Universidade de Taubaté - Engenharia da Computação" 
YEAR        = "2026"

# ── Bilingual report content ─────────────────────────────────────────────────

TEXTS: dict[str, dict] = {
    'en': {
        'title':    "ARTIFICIAL INTELLIGENCE I REPORT",
        'subtitle': "Local Search Algorithms and GA for the Knapsack Problem",
        'members_label': 'Members:',

        'section1_title': "1. INTRODUCTION",
        'section1_text': (
            "This report presents the results of experiments carried out with local "
            "search algorithms and a genetic algorithm applied to the Knapsack Problem "
            "under a travel-time constraint. The problem consists of determining the "
            "best path between two points on a procedurally generated map, composed of "
            "different terrain types — plains, forest, swamp and mountain — each with "
            "its own factor modifying the agent's travel speed."
            "\n\n"
            "The main goal is to maximize the use of the available time (the knapsack's "
            "capacity), finding paths that allow the agent to travel the greatest "
            "possible distance without exceeding the stipulated time limit. The gain of "
            "each solution is calculated relative to the initial solution generated by "
            "breadth-first search (BFS), which serves as the baseline for comparing the "
            "methods."
        ),

        'section2_title': "2. METHODOLOGY",
        'section2_text': (
            "Four local search algorithms were implemented and evaluated, each with "
            "distinct characteristics regarding how they explore the solution space:"
            "\n\n"
            "Hill Climbing (HC): a greedy algorithm that only accepts moves that improve "
            "the current solution's value. It tends to converge quickly, but can get "
            "stuck in local optima."
            "\n\n"
            "Hill Climbing with Random Restart (HCR): a variant that tolerates a maximum "
            "number of iterations without improvement (the TMAX parameter) before "
            "stopping, giving it more resistance to plateaus."
            "\n\n"
            "Simulated Annealing (SA): inspired by the physical process of annealing "
            "metals, it accepts worse solutions with a probability that decreases as the "
            "temperature drops. Its parameters control the initial temperature (TI), the "
            "final temperature (TF) and the cooling factor (FR)."
            "\n\n"
            "Genetic Algorithm (GA): based on mechanisms from biological evolution, it "
            "operates on a population of solutions through selection, crossover and "
            "mutation operators. Its parameters include population size (TP), number of "
            "generations (NG), crossover rate (TC), mutation rate (TM) and elitism "
            "fraction (IG)."
            "\n\n"
            "The initial solution for each run is generated by breadth-first search "
            "(BFS), guaranteeing a valid path between the start and goal states. Each "
            "solution's fitness is calculated as the total travel time within the "
            "established limit, and the percentage gain is obtained from the ratio "
            "between the improvement achieved and the time limit."
            "\n\n"
            "Data was collected using the Comparative Analysis tool built into the "
            "application, which allows each algorithm's parameters to be configured "
            "individually and the number of runs per method to be set. The reported "
            "final cost corresponds to the arithmetic mean of the runs performed, as "
            "does the average percentage gain relative to the initial solution."
        ),

        'section3_title': "3. RESULTS",
        'section3_intro': (
            "The results obtained from the experiments are presented below, including "
            "the comparison table with the main performance indicators for each "
            "configuration tested and the bar chart with the percentage gains achieved."
        ),
        'run_config_text': (
            "Run configuration: time limit of <b>{limit}s</b>, {n_maps}, "
            "start node <b>{start}</b>, goal node <b>{goal}</b>."
        ),
        'n_maps_multi':  '{n} maps',
        'n_maps_single': 'single map',

        'conclusion_template': (
            "In the tests performed, the algorithm with the best result was {method}, "
            "using the {config} configuration, with a time of {time}s for a limit of "
            "{limit}s and a gain of {gain}% relative to the initial solution generated "
            "by BFS."
        ),
        'conclusion_no_result': (
            "It was not possible to determine the best result because no algorithm "
            "found a valid solution."
        ),
        'default_config_label': 'default',

        'table_headers': ['METHOD', 'CONFIGURATION', 'TIME (s)', 'GAIN', 'NODES'],

        'save_dialog_title': 'Save report',
        'save_filename':      'ai_report.pdf',
        'export_success_title':   'Report exported',
        'export_success_message': 'PDF successfully saved to:\n{path}',
        'export_error_title':     'Export error',
    },

    'pt': {
        'title':    "RELATÓRIO DE INTELIGÊNCIA ARTIFICIAL I",
        'subtitle': "Algoritmos de Busca Local e AG no Problema da Mochila",
        'members_label': 'Integrantes:',

        'section1_title': "1. INTRODUÇÃO",
        'section1_text': (
            "Este relatório apresenta os resultados de experimentos realizados com "
            "algoritmos de busca local e algoritmo genético aplicados ao Problema da "
            "Mochila com restrição de tempo de deslocamento. O problema consiste em "
            "determinar o melhor caminho entre dois pontos em um mapa gerado "
            "proceduralmente, composto por diferentes tipos de terreno — planície, "
            "floresta, pântano e montanha — cada qual com um fator de modificação da "
            "velocidade de deslocamento do agente."
            "\n\n"
            "O objetivo principal é maximizar o aproveitamento do tempo disponível "
            "(capacidade da mochila), encontrando caminhos que permitam ao agente "
            "percorrer a maior distância possível sem ultrapassar o limite de tempo "
            "estipulado. O ganho de cada solução é calculado em relação à solução "
            "inicial gerada por busca em largura (BFS), servindo como linha de base "
            "para a comparação entre os métodos."
        ),

        'section2_title': "2. METODOLOGIA",
        'section2_text': (
            "Foram implementados e avaliados quatro algoritmos de busca local, cada um "
            "com características distintas quanto à exploração do espaço de soluções:"
            "\n\n"
            "Subida de Encosta (SE): algoritmo guloso que aceita apenas movimentos que "
            "melhorem o valor da solução corrente. Tende a convergir rapidamente, mas "
            "pode ficar preso em ótimos locais."
            "\n\n"
            "Subida de Encosta com Tentativa (SET): variante que tolera um número "
            "máximo de iterações sem melhora (parâmetro TMAX) antes de encerrar, "
            "conferindo maior resistência a platôs."
            "\n\n"
            "Têmpera Simulada (TS): inspirada no processo físico de resfriamento de "
            "metais, aceita soluções piores com uma probabilidade que decresce com a "
            "temperatura. Os parâmetros controlam a temperatura inicial (TI), a "
            "temperatura final (TF) e o fator de resfriamento (FR)."
            "\n\n"
            "Algoritmo Genético (AG): baseado em mecanismos da evolução biológica, "
            "opera sobre uma população de soluções por meio de operadores de seleção, "
            "cruzamento e mutação. Os parâmetros incluem tamanho da população (TP), "
            "número de gerações (NG), taxa de cruzamento (TC), taxa de mutação (TM) e "
            "fração de elitismo (IG)."
            "\n\n"
            "A solução inicial de cada execução é gerada por busca em largura (BFS), "
            "garantindo um caminho válido entre os estados inicial e objetivo. O "
            "fitness de cada solução é calculado como o tempo total de deslocamento "
            "dentro do limite estabelecido, e o ganho percentual é obtido pela razão "
            "entre a melhoria alcançada e o tempo limite."
            "\n\n"
            "A coleta de dados foi realizada por meio da ferramenta de Análise "
            "Comparativa integrada à aplicação, que permite configurar individualmente "
            "os parâmetros de cada algoritmo e definir o número de execuções por "
            "método. O custo final reportado corresponde à média aritmética das "
            "execuções realizadas, assim como o ganho médio percentual em relação à "
            "solução inicial."
        ),

        'section3_title': "3. RESULTADOS OBTIDOS",
        'section3_intro': (
            "A seguir são apresentados os resultados obtidos nos experimentos, "
            "incluindo a tabela comparativa com os principais indicadores de "
            "desempenho de cada configuração testada e o gráfico de barras com os "
            "ganhos percentuais alcançados."
        ),
        'run_config_text': (
            "Configuração da execução: limite de tempo de <b>{limit}s</b>, {n_maps}, "
            "nó inicial <b>{start}</b>, nó objetivo <b>{goal}</b>."
        ),
        'n_maps_multi':  '{n} mapas',
        'n_maps_single': 'mapa simples',

        'conclusion_template': (
            "Nos testes realizados, o algoritmo que apresentou o melhor resultado foi "
            "{method}, utilizando a configuração {config}, com tempo de {time}s para "
            "um limite de {limit}s e ganho de {gain}% em relação à solução inicial "
            "gerada por BFS."
        ),
        'conclusion_no_result': (
            "Não foi possível determinar o melhor resultado pois nenhum algoritmo "
            "encontrou uma solução válida."
        ),
        'default_config_label': 'padrão',

        'table_headers': ['MÉTODO', 'CONFIGURAÇÃO', 'TEMPO (s)', 'GANHO', 'NÓS'],

        'save_dialog_title': 'Salvar relatório',
        'save_filename':      'relatorio_ia.pdf',
        'export_success_title':   'Relatório exportado',
        'export_success_message': 'PDF salvo com sucesso em:\n{path}',
        'export_error_title':     'Erro ao exportar',
    },
    'es': {
        'title':    "INFORME DE INTELIGENCIA ARTIFICIAL I",
        'subtitle': "Algoritmos de Búsqueda Local y AG para el Problema de la Mochila",
        'members_label': 'Integrantes:',

        'section1_title': "1. INTRODUCCIÓN",
        'section1_text': (
            "Este informe presenta los resultados de experimentos realizados con "
            "algoritmos de búsqueda local y un algoritmo genético aplicados al "
            "Problema de la Mochila bajo una restricción de tiempo de "
            "desplazamiento. El problema consiste en determinar el mejor camino "
            "entre dos puntos en un mapa generado de forma procedural, compuesto "
            "por diferentes tipos de terreno — llanura, bosque, pantano y montaña "
            "— cada uno con su propio factor que modifica la velocidad de "
            "desplazamiento del agente."
            "\n\n"
            "El objetivo principal es maximizar el aprovechamiento del tiempo "
            "disponible (la capacidad de la mochila), encontrando caminos que "
            "permitan al agente recorrer la mayor distancia posible sin superar "
            "el límite de tiempo estipulado. La ganancia de cada solución se "
            "calcula en relación con la solución inicial generada por búsqueda "
            "en anchura (BFS), que sirve como línea base para comparar los "
            "métodos."
        ),

        'section2_title': "2. METODOLOGÍA",
        'section2_text': (
            "Se implementaron y evaluaron cuatro algoritmos de búsqueda local, "
            "cada uno con características distintas en cuanto a la forma de "
            "explorar el espacio de soluciones:"
            "\n\n"
            "Ascenso de Colinas (AC): un algoritmo voraz que solo acepta "
            "movimientos que mejoren el valor de la solución actual. Tiende a "
            "converger rápidamente, pero puede quedar atrapado en óptimos "
            "locales."
            "\n\n"
            "Ascenso de Colinas con Reinicio Aleatorio (ACR): una variante que "
            "tolera un número máximo de iteraciones sin mejora (parámetro TMAX) "
            "antes de detenerse, dándole mayor resistencia a las mesetas."
            "\n\n"
            "Recocido Simulado (RS): inspirado en el proceso físico de recocido "
            "de metales, acepta soluciones peores con una probabilidad que "
            "disminuye a medida que baja la temperatura. Sus parámetros "
            "controlan la temperatura inicial (TI), la temperatura final (TF) y "
            "el factor de enfriamiento (FR)."
            "\n\n"
            "Algoritmo Genético (AG): basado en mecanismos de la evolución "
            "biológica, opera sobre una población de soluciones mediante "
            "operadores de selección, cruce y mutación. Sus parámetros incluyen "
            "el tamaño de la población (TP), el número de generaciones (NG), la "
            "tasa de cruce (TC), la tasa de mutación (TM) y la fracción de "
            "elitismo (IG)."
            "\n\n"
            "La solución inicial de cada ejecución se genera mediante búsqueda "
            "en anchura (BFS), garantizando un camino válido entre los estados "
            "inicial y objetivo. El fitness de cada solución se calcula como el "
            "tiempo total de desplazamiento dentro del límite establecido, y la "
            "ganancia porcentual se obtiene de la razón entre la mejora lograda "
            "y el límite de tiempo."
            "\n\n"
            "Los datos se recopilaron mediante la herramienta de Análisis "
            "Comparativo integrada en la aplicación, que permite configurar "
            "individualmente los parámetros de cada algoritmo y definir el "
            "número de ejecuciones por método. El costo final reportado "
            "corresponde a la media aritmética de las ejecuciones realizadas, "
            "al igual que la ganancia porcentual promedio en relación con la "
            "solución inicial."
        ),

        'section3_title': "3. RESULTADOS",
        'section3_intro': (
            "A continuación se presentan los resultados obtenidos en los "
            "experimentos, incluyendo la tabla comparativa con los principales "
            "indicadores de rendimiento de cada configuración probada y el "
            "gráfico de barras con las ganancias porcentuales alcanzadas."
        ),
        'run_config_text': (
            "Configuración de la ejecución: límite de tiempo de <b>{limit}s</b>, "
            "{n_maps}, nodo inicial <b>{start}</b>, nodo objetivo <b>{goal}</b>."
        ),
        'n_maps_multi':  '{n} mapas',
        'n_maps_single': 'mapa único',

        'conclusion_template': (
            "En las pruebas realizadas, el algoritmo con el mejor resultado fue "
            "{method}, utilizando la configuración {config}, con un tiempo de "
            "{time}s para un límite de {limit}s y una ganancia del {gain}% en "
            "relación con la solución inicial generada por BFS."
        ),
        'conclusion_no_result': (
            "No fue posible determinar el mejor resultado porque ningún "
            "algoritmo encontró una solución válida."
        ),
        'default_config_label': 'predeterminada',

        'table_headers': ['MÉTODO', 'CONFIGURACIÓN', 'TIEMPO (s)', 'GANANCIA', 'NODOS'],

        'save_dialog_title': 'Guardar informe',
        'save_filename':      'informe_ia.pdf',
        'export_success_title':   'Informe exportado',
        'export_success_message': 'PDF guardado correctamente en:\n{path}',
        'export_error_title':     'Error al exportar',
    },
}


def get_text(key: str, lang: str = 'en', **kwargs) -> str:
    """Look up a report text by key for the given language, formatting with
    kwargs if provided. Falls back to English if the language or key is
    unknown."""
    template = TEXTS.get(lang, TEXTS['en']).get(key, TEXTS['en'].get(key, key))
    return template.format(**kwargs) if kwargs else template